Watch for dynamically added content within accordion body
engrnvd/u pull request #1
Opened 2024-03-08 11:20 UTC by muhammad-ali-pk

In a scenario where you're adding/toggling dynamic content within accordion body, the height is not automatically updated which results in either clipped overflow, or empty space. This PR fixes this issue.

2024-03-08 11:24 UTC, engrnvd requested changes
I think updateHeight() should have additional call before `const observer`

2024-03-08 11:43 UTC, muhammad-ali-pk commented
> I think updateHeight() should have additional call before `const observer`

No need, the observer triggers it for you as soon as the component mounts.

2024-05-29 11:22 UTC, engrnvd reviewed
Why is labelFn removed?

2024-05-29 11:30 UTC, engrnvd approved these changes

2024-05-29 11:30 UTC, merged